apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-csi
  namespace: default
  labels: &labels
    app: example-csi
spec:
  replicas: 3
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: writer
          image: perovmpr/file-writer:0.0.1
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: csi-s3-pvc
