apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: default
  labels: &labels
    name: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: mysql-operator
      containers:
        - name: mysql-operator
          image: roflmaoinmysoul/mysql-operator:1.0.0
