repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argo
    namespace: argocd
    chart: argo/argo-cd
    version: 7.7.11
    values:
      - global:
          tolerations:
            - key: node-role
              operator: Equal
              value: infra
              effect: NoSchedule
          affinity:
            nodeAffinity:
              type: hard
              matchExpressions:
                - key: node-role.kubernetes.io
                  operator: In
                  values:
                    - infra
      - redis-ha:
          enabled: true
          affinity: |
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io
                        operator: In
                        values:
                        - infra
          tolerations:
            - key: node-role
              operator: Equal
              value: infra
              effect: NoSchedule
          haproxy:
            affinity: |
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node-role.kubernetes.io
                          operator: In
                          values:
                          - infra
            tolerations:
              - key: node-role
                operator: Equal
                value: infra
                effect: NoSchedule

      - controller:
          replicas: 1

      - server:
          replicas: 2

      - repoServer:
          replicas: 2

      - applicationSet:
          replicas: 2