apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-service-monitor
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: metrics