apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  default.conf.template: |
    server {
        listen ${DEFAULT_PORT} deferred reuseport default;
        listen [::]:${DEFAULT_PORT} deferred reuseport default;
        charset utf-8;
        root ${DEFAULT_HOME_DIR};
        index index.html;
            location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
  status.conf: |
    server {
    listen 8080;
    access_log off;
      location /server-status {
          stub_status on;
      }
    }