apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: my-app-nginx
  labels:
    app: my-app
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: my-app