apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-otus-external-secret
  namespace: vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-otus-secret-store
    kind: SecretStore
  target:
    name: vault-otus-secret
  data:
    - secretKey: username
      remoteRef:
        key: cred
        property: username
    - secretKey: password
      remoteRef:
        key: cred
        property: password
