repositories:
  - name: consul
    url: git+https://github.com/hashicorp/consul-k8s@charts/consul?ref=v1.6.2&sparse=0
  - name: vault
    url: git+https://github.com/hashicorp/vault-helm@/?ref=v0.29.1&sparse=0
  - name: external-secrets
    url: https://external-secrets.io

releases:
  - name: consul
    namespace: consul
    chart: consul/consul
    version: 1.6.2
    values:
      - server:
          replicas: 3
  - name: vault
    namespace: vault
    chart: vault/vault
    version: 0.29.1
    values:
      - server:
          ha:
            enabled: true
            replicas: 3
            config: |
              ui = true
  
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "consul" {
                path = "vault"
                address = "consul-consul-server.consul.svc.cluster.local:8500"
              }


  - name: external-secrets
    namespace: vault
    chart: external-secrets/external-secrets
    version: 0.13.0
