apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-otus-secret-store
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "/otus"
      version: "v1"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "otus"
          serviceAccountRef:
            name: vault-auth
            namespace: vault