apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-chart.name" . }}
data:
  default.conf.template: |
    server {
        listen ${DEFAULT_PORT} deferred reuseport default;
        listen [::]:${DEFAULT_PORT} deferred reuseport default;
        charset utf-8;
        root ${DEFAULT_HOME_DIR};
        index index.html;
            location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
  index.html: |
    <!doctype html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
      </head>
      <body>
        <p> config/file </p>
      </body>
      </html>

  app: my-app
  user: my-user
  token: my-token
