apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-chart.name" . }}
spec:
  accessModes: {{ .Values.persistentVolumeClaim.accessModes }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.resourcesRequestsStorage }}