{{ $serviceAccountCdName := include "my-chart.default.name" .Values.serviceAccount.cd -}}
{{ $roleCdName := include "my-chart.default.name" .Values.role.namespaceAdmin -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-%s" $serviceAccountCdName $roleCdName | trunc 63 | trimSuffix "-" }}
subjects:
  - kind: ServiceAccount
    name: {{ include "my-chart.default.name" .Values.serviceAccount.cd }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "my-chart.default.name" .Values.role.namespaceAdmin }}
  apiGroup: rbac.authorization.k8s.io
---
{{ $serviceAccountMonitoringName := include "my-chart.default.name" .Values.serviceAccount.monitoring -}}
{{ $roleMonitoringName := include "my-chart.default.name" .Values.role.clusterMonitoring -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s-%s"  $serviceAccountMonitoringName $roleMonitoringName .Release.Name  | trunc 63 | trimSuffix "-" }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountMonitoringName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $roleMonitoringName }}
  apiGroup: rbac.authorization.k8s.io