---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.role.namespaceAdmin.kind}}
metadata:
  name: {{ include "my-chart.default.name" .Values.role.namespaceAdmin }}
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.role.clusterMonitoring.kind}}
metadata:
  name: {{ include "my-chart.default.name" .Values.role.clusterMonitoring }}
rules:
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---