---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.name" . }}
  labels: &labels
    {{ include "my-chart.labels" .  | nindent 4 }}
spec:
  selector: *labels
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.portName }}