{{- range $service, $serviceAccount := .Values.serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- default $serviceAccount.default $serviceAccount.name | indent  1 }}
  labels:
    account: {{ $service | quote }}
{{- end }}